spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    address: 127.0.0.1
    port: 5672
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
wx:
  appid: 請輸入微信appid
  mchid: 請輸入微信mchid
  mchkey: 請輸入微信mchkey
  notifyUrl: http://127.0.0.1/pay/notify
  returnUrl: http://127.0.0.1
alipay:
  appid: 請輸入支付寶appid
  privateKey: 請輸入支付寶privateKey
  publicKey: 請輸入支付寶publicKey
  notifyUrl: http://127.0.0.1/pay/notify
  returnUrl: http://127.0.0.1
server:
  port: 8082
thymeleaf:
  cache: false
  prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
  suffix: .html
  encoding: UTF-8
  mode: HTML5